version: '3.8'

networks:
  redisnet:
    driver: bridge
    external: true

services:

  redis-cluster:
    container_name: redis-cluster
    image: redis:latest
    command: redis-cli -p 7001 --cluster create 10.0.0.11:7001 10.0.0.12:7002 10.0.0.13:7003 10.0.0.14:7004 10.0.0.15:7005 10.0.0.16:7006 --cluster-replicas 1 --cluster-yes
    ports:
    - 6379:6379
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
    networks:
      - redisnet
    environment:
      REDIS_PASSWORD: 'bitnami'

  redis-1:
    image: redis:latest
    container_name: redis-1
    networks:
      - redisnet
    ports:
      - 7001:6379

  redis-2:
    image: redis:latest
    container_name: redis-2
    networks:
      - redisnet
    ports:
      - 7002:6379

  redis-3:
    image: redis:latest
    container_name: redis-3
    networks:
      - redisnet
    ports:
      - 7003:6379

  redis-4:
    image: redis:latest
    container_name: redis-4
    networks:
      - redisnet
    ports:
      - 7004:6379

  redis-5:
    image: redis:latest
    container_name: redis-5
    networks:
      - redisnet
    ports:
      - 7005:6379

  redis-6:
    image: redis:latest
    container_name: redis-6
    networks:
      - redisnet
    ports:
      - 7006:6379